# Generated by Django 5.1.5 on 2025-01-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_1', models.TextField(blank=True, null=True)),
                ('choice_2', models.TextField(blank=True, null=True)),
                ('choice_3', models.TextField(blank=True, null=True)),
                ('choice_4', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
            ],
        ),
    ]
