# Generated by Django 5.1.5 on 2025-01-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python')], default='JavaScript', help_text='Select the category for this question.', max_length=50),
        ),
    ]
