# Generated by Django 5.1.5 on 2025-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('SQL', 'SQL'), ('Flashcard', 'Flashcard')], default='JavaScript', help_text='Select the category for this question.', max_length=50),
        ),
    ]
