# Generated by Django 5.1.5 on 2025-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Flashcard', 'Flashcard'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('SQL', 'SQL'), ('Git', 'Git')], default='JavaScript', help_text='Select the category for this question.', max_length=50),
        ),
    ]
