# Generated by Django 5.1.5 on 2025-01-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='points',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='score',
            name='project',
        ),
    ]
