# Generated by Django 5.1.5 on 2025-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_date_score_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Flashcard', 'Flashcard'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('SQL', 'SQL'), ('Git', 'Git'), ('Randon', 'Randon')], default='JavaScript', help_text='Select the category for this question.', max_length=50),
        ),
    ]
