# Generated by Django 5.1.5 on 2025-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='choice_1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='choice_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='choice_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='choice_4',
            field=models.TextField(),
        ),
    ]
