# Generated by Django 5.1.5 on 2025-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_project_choice_1_alter_project_choice_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='choice_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='choice_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='choice_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='choice_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
