# Generated by Django 5.1.5 on 2025-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_project_choice_1_alter_project_choice_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Flashcard', 'Flashcard'), ('JavaScript', 'JavaScript'), ('JavaScript Level 2', 'JavaScript Level 2'), ('Python', 'Python'), ('SQL', 'SQL'), ('Git', 'Git'), ('Randon', 'Randon')], default='JavaScript', help_text='Select the category for this question.', max_length=50),
        ),
    ]
