# Generated by Django 5.1.5 on 2025-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('JavaScript Level 2', 'JavaScript Level 2'), ('JavaScript Level 3', 'JavaScript Level 3'), ('Python', 'Python'), ('Python Level 2', 'Python Level 2'), ('Python Level 3', 'Python Level 3'), ('SQL', 'SQL'), ('SQL Level 2', 'SQL Level 2'), ('SQL Level 3', 'SQL Level 3'), ('Git', 'Git'), ('Git Level 2', 'Git Level 2'), ('Git Level 3', 'Git Level 3'), ('Randon', 'Randon')], default='JavaScript', help_text='Select the category for this question.', max_length=50),
        ),
    ]
