# Generated by Django 5.1.5 on 2025-02-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Flashcard', 'Flashcard'), ('JavaScript', 'JavaScript'), ('JavaScriptL_2', 'JavaScript_2'), ('Python', 'Python'), ('Python level 2', 'Python level 2'), ('SQL', 'SQL'), ('SQL level 2', 'SQL level 2'), ('Git', 'Git'), ('Git level 2', 'Git level 2'), ('Randon', 'Randon')], default='JavaScript', help_text='Select the category for this question.', max_length=50),
        ),
    ]
