# Generated by Django 6.0.1 on 2026-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Flashcard', 'Flashcard'), ('JavaScript', 'JavaScript'), ('JavaScriptL_2', 'JavaScript_2'), ('Python', 'Python'), ('PythonL_2', 'PythonL_2'), ('SQL', 'SQL'), ('SQL_level_2', 'SQL_level_2'), ('Git', 'Git'), ('Git_level_2', 'Git_level_2'), ('Randon', 'Randon'), ('Exercises - Int', 'Exercises - Int')], default='JavaScript', help_text='Select the category for this question.', max_length=50),
        ),
    ]
